import type { Metadata } from "next";
import localFont from "next/font/local"; // localFont 임포트
import "./globals.css";

// Pretendard 폰트 설정
const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2", // 폰트 파일 경로 수정
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}> {/* Pretendard 폰트 적용 */}
        {children}
      </body>
    </html>
  );
}